const propertiesData = [
    {
        id: 1,
        title: "Villa Lumina",
        location: "Bonanjo",
        price: 80500000,
        type: "villa",
        beds: 5,
        baths: 6,
        sqft: 850,
        image: "maison/47239_00-2025-06-04-0127.jpg",
        description: "Chef-d'œuvre architectural au cœur de Bonanjo. Cette villa contemporaine offre des finitions exceptionnelles, une piscine privée et un design moderne parfaitement intégré au quartier administratif de Douala."
    },
    {
        id: 2,
        title: "Penthouse Étoile",
        location: "Bonamoussadi",
        price: 40200000,
        type: "penthouse",
        beds: 3,
        baths: 3,
        sqft: 280,
        image: "maison/photo-1512918728675-ed5a9ecdebfd.avif",
        description: "Spectaculaire penthouse avec vue imprenable sur Bonamoussadi. Ce bijou dispose de volumes généreux et d'équipements domotiques de pointe pour un confort urbain absolu."
    },
    {
        id: 3,
        title: "Domaine des Arcs",
        location: "Bonapriso",
        price: 60300000,
        type: "villa",
        beds: 7,
        baths: 8,
        sqft: 1200,
        image: "maison/photo-1510798831971-661eb04b3739.avif",
        description: "Villa ultra-luxe située dans le quartier résidentiel prisé de Bonapriso. Un espace de vie grandiose avec jardin paysager, piscine et sécurité renforcée."
    },
    {
        id: 4,
        title: "Appartement Haussmannien",
        location: "Akwa",
        price: 20850000,
        type: "apartment",
        beds: 2,
        baths: 2,
        sqft: 165,
        image: "maison/photo-1493809842364-78817add7ffb.avif",
        description: "Superbe appartement rénové au cœur d'Akwa. Alliant charme classique et modernité, ce bien offre une proximité immédiate avec les centres d'affaires et commerciaux."
    },
    {
        id: 5,
        title: "Villa Horizon",
        location: "Yassa",
        price: 100000000,
        type: "villa",
        beds: 6,
        baths: 7,
        sqft: 1100,
        image: "maison/photo-1600596542815-ffad4c1539a9.avif",
        description: "Propriété de prestige sur les hauteurs de Yassa. Entièrement sécurisée, elle propose un vaste jardin, un garage multiple et des finitions de très haut standing."
    },
    {
        id: 6,
        title: "Le Duplex Royal",
        location: "Bali",
        price: 30100000,
        type: "apartment",
        beds: 4,
        baths: 3,
        sqft: 220,
        image: "maison/photo-1522708323590-d24dbb6b0267.avif",
        description: "Duplex contemporain situé à Bali. Design minimaliste et spacieux, idéal pour une vie de famille dynamique dans un quartier central."
    },
    {
        id: 7,
        title: "Villa d'Azur",
        location: "Bonanjo",
        price: 50400000,
        type: "villa",
        beds: 4,
        baths: 4,
        sqft: 450,
        image: "maison/images (6).jpeg",
        description: "Une villa d'exception située dans le calme de Bonanjo. Décoration raffinée et espace extérieur avec piscine pour une détente totale."
    },
    {
        id: 8,
        title: "Manoir du Lac",
        location: "Akwa",
        price: 70200000,
        type: "villa",
        beds: 8,
        baths: 7,
        sqft: 900,
        image: "maison/images (7).jpeg",
        description: "Demeure de caractère au style unique, offrant de vastes réceptions et un confort moderne au cœur du centre névralgique de Douala."
    },
    {
        id: 9,
        title: "Appartement Belle-Vue",
        location: "Bonapriso",
        price: 10950000,
        type: "apartment",
        beds: 3,
        baths: 2,
        sqft: 140,
        image: "maison/images (8).jpeg",
        description: "Appartement lumineux avec balcon offrant une vue dégagée sur Bonapriso. Rénovation de qualité et agencement fonctionnel."
    },
    {
        id: 10,
        title: "Chalet des Cimes",
        location: "Yassa",
        price: 40800000,
        type: "villa",
        beds: 5,
        baths: 5,
        sqft: 380,
        image: "maison/images (9).jpeg",
        description: "Résidence moderne située à Yassa. Alliant confort et sécurité, cette maison est parfaite pour s'éloigner du tumulte du centre-ville."
    },
    {
        id: 11,
        title: "Résidence de Mer",
        location: "Bonamoussadi",
        price: 90000000,
        type: "villa",
        beds: 6,
        baths: 6,
        sqft: 600,
        image: "maison/images (10).jpeg",
        description: "Propriété d'exception à Bonamoussadi. Vastes pièces de vie, jardin arboré et piscine privée pour un cadre de vie prestigieux."
    },
    {
        id: 12,
        title: "Villa Cascade",
        location: "Bali",
        price: 30500000,
        type: "villa",
        beds: 5,
        baths: 4,
        sqft: 320,
        image: "maison/OIP.webp",
        description: "Villa contemporaine nichée dans un quartier calme de Bali. Design épuré et grandes ouvertures apportant une luminosité naturelle."
    },
    {
        id: 13,
        title: "Résidence des Pins",
        location: "Bonanjo",
        price: 20200000,
        type: "villa",
        beds: 4,
        baths: 3,
        sqft: 250,
        image: "maison/OIP (1).webp",
        description: "Demeure de charme entourée de verdure à Bonanjo. Un mélange parfait de style traditionnel et d'aménagements modernes."
    },
    {
        id: 14,
        title: "Appartement Lumière",
        location: "Bonanjo",
        price: 10100000,
        type: "apartment",
        beds: 2,
        baths: 2,
        sqft: 110,
        image: "maison/OIP (2).webp",
        description: "Appartement d'exception au cœur du centre administratif, offrant calme et élégance pour une clientèle exigeante."
    },
    {
        id: 15,
        title: "Villa Serena",
        location: "Akwa",
        price: 60800000,
        type: "villa",
        beds: 6,
        baths: 6,
        sqft: 550,
        image: "maison/OIP (3).webp",
        description: "Sérénité et luxe au cœur d'Akwa. Une propriété spacieuse avec tout le confort moderne nécessaire."
    },
    {
        id: 16,
        title: "Penthouse Sky",
        location: "Bonamoussadi",
        price: 20500000,
        type: "penthouse",
        beds: 3,
        baths: 2,
        sqft: 190,
        image: "maison/OIP (4).webp",
        description: "Penthouse spectaculaire surplombant Bonamoussadi avec une terrasse privée offrant une vue panoramique."
    },
    {
        id: 17,
        title: "Domaine du Verdon",
        location: "Yassa",
        price: 40900000,
        type: "villa",
        beds: 7,
        baths: 5,
        sqft: 600,
        image: "maison/OIP (5).webp",
        description: "Grande propriété familiale à Yassa, offrant calme et espace sur un terrain sécurisé."
    },
    {
        id: 18,
        title: "Loft Industriel",
        location: "Bali",
        price: 10450000,
        type: "apartment",
        beds: 2,
        baths: 1,
        sqft: 150,
        image: "maison/OIP (6).webp",
        description: "Espace atypique transformé en appartement moderne à Bali. Grands volumes et design contemporain."
    },
    {
        id: 19,
        title: "Villa des Oliviers",
        location: "Bali",
        price: 30200000,
        type: "villa",
        beds: 5,
        baths: 4,
        sqft: 300,
        image: "maison/OIP (7).webp",
        description: "Villa chaleureuse située dans une ruelle paisible de Bali. Parfait pour une famille cherchant la proximité du centre."
    },
    {
        id: 20,
        title: "Le Refuge Moderne",
        location: "Bonamoussadi",
        price: 50750000,
        type: "villa",
        beds: 4,
        baths: 4,
        sqft: 420,
        image: "maison/OIP (8).webp",
        description: "Résidence d'exception alliant architecture moderne et confort à Bonamoussadi."
    },
    {
        id: 21,
        title: "Villa d'Exception",
        location: "Bonanjo",
        price: 108000000,
        type: "villa",
        beds: 6,
        baths: 7,
        sqft: 950,
        image: "maison/télécharger.webp",
        description: "Une propriété unique surplombant le quartier de Bonanjo, offrant une intimité totale et un luxe sans compromis."
    }
];
